os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
script:
  - . ./.travis.sh # conditionally installs Swift 2.2 on Linux
  - export PATH=$TRAVIS_BUILD_DIR/swift-2.2-RELEASE-ubuntu14.04/usr/bin/:"${PATH}" # adds Swift 2.2 to PATH
  - make # compiles project with Swift 2.2
  - sudo make install # installs shared libs and CLI
  - vapor build Sources/VaporDev/main.swift Sources/VaporDev/**/*.swift # builds VaporDev with CLI
  - rm -rf Packages .build # cleans project to prevent conflicts between 2.2 and 3.0
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)" # Installs swiftenv
  - swift build --fetch # clones all dependencies
  - rm -rf Packages/*/Tests # fixes SPM bug
  - swift build 
  - swift test
