language: swift

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -project Vapor.xcodeproj -scheme Vapor
- xctool test -project Vapor.xcodeproj -scheme Tests