os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
  - sudo apt-get install -y build-essential libssl-dev git
  - git clone https://github.com/wg/wrk.git
  - cd wrk
  - make
  - sudo cp wrk /usr/local/bin
script:
  - swift build --fetch # clones all dependencies
  - rm -rf Packages/*/Tests
  - swift build
  - swift build --configuration release
  - swift test
  - .build/release/Performance --port=8523 --env=production &
  - wrk -d 10 -t 4 -c 128 http://localhost:8523/plaintext
