#language: objective-c

#before_install:
#- brew update
#- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

#script:
#- touch /Users/travis/build/tannernelson/vapor/Sources/main.swift
#- xctool clean build -project Vapor.xcodeproj -scheme Vapor
#- xctool test -project Vapor.xcodeproj -scheme Tests

language: generic

sudo: required
dist: trusty

install:
- mkdir swift
- curl https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a/swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null

script:
- env PATH=$(pwd)/swift/swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a-ubuntu14.04/usr/bin:$PATH swift build